 const menuList = [
   
        {
            id: 1,
            name: 'Classic Veg Burger',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 2,
            name: 'Classic Paneer Burger',
            price: 49,
            flag: false,
            count: 0,
        },
        {
            id: 3,
            name: 'Loaded Cheese Burger',
            price: 39,
            flag: false,
            count: 0,

        },
        {
            id: 4,
            name: 'Double Patty Veg Burger',
            price: 59,
            flag: false,
            count: 0,
        },
        {
            id: 5,
            name: 'Pluto Special Burger',
            price: 69,
            flag: false,
            count: 0,
        },
    
        {
            id: 6,
            name: 'Classic Frech Fries',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 7,
            name: 'Peri-Peri French Fries',
            price: 35,
            flag: false,
            count: 0,
        },
        {
            id: 8,
            name: 'Cheese French Fries',
            price: 35,
            flag: false,
            count: 0,
        },
        {
            id: 9,
            name: 'Masala French Fries',
            price: 35,
            flag: false,
            count: 0,
        },
        {
            id: 10,
            name: 'Classic Veg Sandwich',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 11,
            name: 'Creamy Malai Sandwich',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 12,
            name: 'Masala Sandwich',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 13,
            name: 'Classic Veg with loaded Chessse Sandwich',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 14,
            name: 'Classic Banana Sandwich',
            price: 29,
        },
        {
            id: 15,
            name: 'Pluto Special Sandwich',
            price: 69,
            flag: false,
            count: 0,
        },

        {
            id: 16,
            name: 'Classic Veg Maggie',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 17,
            name: 'Veg Maggie with Cheese blast',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 18,
            name: 'Spicy Masala Maggie',
            price: 35,
            flag: false,
            count: 0,
        },
        {
            id: 19,
            name: 'Plain Butter Maggie',
            price: 25,
            flag: false,
            count: 0,
        },
        {
            id: 20,
            name: 'Hot Schezwan Maggie',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 21,
            name: 'Soupy Maggie',
            price: 25,
            flag: false,
            count: 0,
        },
        {
            id: 22,
            name: 'Cheese Corn Maggie',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 23,
            name: 'Masala Twister',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 24,
            name: 'Peri-Peri Cheese Twister',
            price: 35,
            flag: false,
            count: 0,
        },
        {
            id: 25,
            name: 'Hot Schezwan Twister',
            price: 49,
            flag: false,
            count: 0,
        },
        {
            id: 26,
            name: 'Pluto Potato Twister',
            price: 49,
            flag: false,
            count: 0,
        },
        {
            id: 27,
            name: 'Pluto Iced Coffee',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 28,
            name: 'Frappuccino',
            price: 29,
            flag: false,
            count: 0,
        },
        {
            id: 29,
            name: 'Iced Mocha',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 30,
            name: 'Classic Cold Coffee',
            price: 29,
            flag: false,
            count: 0,
        },
    
        {
            id: 31,
            name: 'Pluto Freek shake Coffee',
            price: 39,
            flag: false,
            count: 0,
        },
        {
            id: 32,
            name: 'Hot Coffee',
            price: 9,
            flag: false,
            count: 0,
        },
        {
            id: 33,
            name: 'Filter Coffee',
            price: 9,
            flag: false,
            count: 0,
        },
        {
            id: 34,
            name: 'Masala Ginger Tea',
            price: 9,
            flag: false,
            count: 0,
        },
       
        {
            id: 35,
            name: 'Classic Veg Burger + French Fries + Classic Cold Coffee',
            price: 69,
            flag: false,
            count: 0,
        },
        {
            id: 36,
            name: 'Classic Veg Burger + French Fries + Coke',
            price: 69,
            flag: false,
            count: 0,
        },
        {
            id: 37,
            name: 'Classic Veg Maggie + Classic Cold Coffee',
            price: 49,
            flag: false,
            count: 0,
        },
        {
            id: 38,
            name: 'Maggie + Coke + French Fries',
            price: 69,
            flag: false,
            count: 0,
        },
        {
            id: 39,
            name: 'Masala Twister + Classic Cold coffee + Classic Veg Maggie',
            price: 69,
            flag: false,
            count: 0,
        },

        {
            id: 40,
            name: 'Masala Twister + Coke + Maggie',
            price: 69,
            flag: false,
            count: 0,
        },
        {
            id: 41,
            name: 'Classic Veg Sandwitch + French Fries + Coke',
            price: 69,
            flag: false,
            count: 0,
        },
        {
            id: 42,
            name: 'Classic Veg Sandwitch + French Fries + Coke',
            price: 69,
            flag: false,
            count: 0,
        },
        {
            id: 43,
            name: 'Classic Veg Sandwitch + Tea/Coffee',
            price: 39,
            flag: false,
            count: 0,
        },
        
]

export default menuList;